/**
 * fal.ai 3D model generation — server-only.
 *
 * Public API:
 *   - generateModel3D({ mode: "text_to_3d", prompt })
 *   - generateModel3D({ mode: "image_to_3d", imageUrl })
 *
 * Strategy:
 *   • `image_to_3d` — call fal-ai/trellis directly with the user's image
 *     URL. Returns a GLB mesh URL.
 *   • `text_to_3d`  — chain: generate a clean, 3D-friendly product
 *     mockup via fal-ai/flux/schnell, then feed THAT image into trellis.
 *     This re-uses our `generateOneVisual()` helper so the same key/
 *     timeout/fallback discipline applies to the intermediate step.
 *
 * Like the 2D generator, `generateModel3D()` is documented to never
 * throw. All failure paths produce a `status: "fallback"` result with
 * an empty `modelUrl` and a populated `error` string.
 *
 * Key safety: FAL_KEY is only read from process.env and only inside
 * server-side modules. We never echo it in responses or logs.
 */

import { fal } from "@fal-ai/client";

import { generateOneVisual } from "./fal-generation";

/* ─────────────────────────────────────────────────────────────
   Endpoint + constants
   ───────────────────────────────────────────────────────────── */

/**
 * fal.ai's TRELLIS endpoint — image-to-3D, returns GLB.
 * See https://fal.ai/models/fal-ai/trellis/api
 */
export const TRELLIS_MODEL = "fal-ai/trellis";

/* ─────────────────────────────────────────────────────────────
   Lazy fal config (independent cache from fal-generation.ts; both
   calling fal.config with the same key is an idempotent no-op).
   ───────────────────────────────────────────────────────────── */

let _falConfigured: boolean | undefined;

function isUsableFalKey(key: string | undefined): key is string {
  if (!key) return false;
  const trimmed = key.trim();
  if (trimmed.length < 20) return false;
  if (trimmed.toLowerCase().startsWith("your_")) return false;
  if (trimmed.toLowerCase().includes("changeme")) return false;
  return true;
}

function ensureFalConfigured(): boolean {
  if (_falConfigured !== undefined) return _falConfigured;
  const key = process.env.FAL_KEY;
  if (!isUsableFalKey(key)) {
    console.warn(
      "[fal-3d] FAL_KEY missing or placeholder — 3D generation will fall back.",
    );
    _falConfigured = false;
    return false;
  }
  fal.config({ credentials: key });
  _falConfigured = true;
  return true;
}

/* ─────────────────────────────────────────────────────────────
   Types
   ───────────────────────────────────────────────────────────── */

export type Model3DStatus = "generated" | "fallback";
export type Model3DMode = "text_to_3d" | "image_to_3d";

export interface Model3DSuccess {
  status: "generated";
  mode: Model3DMode;
  /** GLB URL returned by trellis. */
  modelUrl: string;
  /** Always "glb" for trellis output. */
  modelType: "glb";
  /** Echoed from the text-to-3D input. */
  prompt?: string;
  /** Echoed from the image-to-3D input. */
  sourceImageUrl?: string;
  /**
   * The intermediate image generated by flux during a text-to-3D
   * chain (text → image → 3D). Useful for the UI to show what was
   * sent to trellis.
   */
  intermediateImageUrl?: string;
  durationMs: number;
}

export interface Model3DFallback {
  status: "fallback";
  mode: Model3DMode;
  modelUrl: "";
  modelType: "glb";
  prompt?: string;
  sourceImageUrl?: string;
  intermediateImageUrl?: string;
  error: string;
  durationMs: number;
}

export type Model3DResult = Model3DSuccess | Model3DFallback;

export type Model3DInput =
  | { mode: "text_to_3d"; prompt: string }
  | { mode: "image_to_3d"; imageUrl: string };

/* ─────────────────────────────────────────────────────────────
   Data URL → fal.storage hoist

   Trellis (and most fal models) require a fully public image URL.
   When the chat lets users upload an image directly we receive a
   `data:image/...;base64,...` URL — convenient client-side, but
   useless to trellis. Detect data URLs and re-host them on
   fal.storage so the rest of the pipeline can stay URL-only.
   ───────────────────────────────────────────────────────────── */

const DATA_URL_RE = /^data:([^;]+);base64,(.+)$/;

function isDataUrl(url: string): boolean {
  return DATA_URL_RE.test(url);
}

/** Decode a `data:` URL into a Blob ready for fal.storage.upload. */
function decodeDataUrl(url: string): { blob: Blob; mime: string } | null {
  const match = url.match(DATA_URL_RE);
  if (!match) return null;
  const [, mime, b64] = match;
  try {
    const buf = Buffer.from(b64, "base64");
    if (buf.byteLength === 0) return null;
    return { blob: new Blob([buf], { type: mime }), mime };
  } catch {
    return null;
  }
}

/**
 * If `imageUrl` is a `data:` URL, upload it to fal.storage and return
 * the resulting public URL. Otherwise pass it through unchanged.
 *
 * Returns `{ ok: false, error }` only on actual upload failure — never
 * throws so the caller's `Model3DResult` discipline stays intact.
 */
async function hoistImageUrl(
  imageUrl: string,
): Promise<{ ok: true; url: string } | { ok: false; error: string }> {
  if (!isDataUrl(imageUrl)) return { ok: true, url: imageUrl };

  const decoded = decodeDataUrl(imageUrl);
  if (!decoded) {
    return { ok: false, error: "data URL was malformed or empty" };
  }

  try {
    // fal.storage.upload accepts File | Blob and returns a string URL.
    const remoteUrl = await fal.storage.upload(decoded.blob);
    if (!remoteUrl || typeof remoteUrl !== "string") {
      return { ok: false, error: "fal.storage.upload returned no URL" };
    }
    return { ok: true, url: remoteUrl };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[fal-3d] fal.storage.upload failed", {
      mime: decoded.mime,
      bytes: decoded.blob.size,
      error: message,
    });
    return { ok: false, error: `fal.storage.upload failed: ${message}` };
  }
}

/* ─────────────────────────────────────────────────────────────
   Trellis internal call
   ───────────────────────────────────────────────────────────── */

interface TrellisOutput {
  model_mesh?: {
    url?: string;
    content_type?: string;
    file_name?: string;
    file_size?: number;
  };
}

interface TrellisSuccess {
  ok: true;
  url: string;
}
interface TrellisFailure {
  ok: false;
  error: string;
}

/**
 * Single trellis call. Wraps the raw SDK call so the caller doesn't
 * have to know about TRELLIS_MODEL / output shape / error handling.
 */
async function callTrellis(imageUrl: string): Promise<TrellisSuccess | TrellisFailure> {
  try {
    const result = await fal.subscribe(TRELLIS_MODEL, {
      input: {
        image_url: imageUrl,
        // Defaults are fine for a hackathon. Higher steps = better
        // quality but ~2× the wall time.
      },
      logs: false,
    });

    const data = result?.data as TrellisOutput | undefined;
    const url = data?.model_mesh?.url;

    if (!url || typeof url !== "string") {
      console.error("[fal-3d] trellis returned no model_mesh.url", {
        imageUrlPreview: imageUrl.slice(0, 80),
      });
      return { ok: false, error: "trellis returned no model_mesh.url" };
    }

    return { ok: true, url };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[fal-3d] trellis call failed", {
      imageUrlPreview: imageUrl.slice(0, 80),
      error: message,
    });
    return { ok: false, error: message };
  }
}

/* ─────────────────────────────────────────────────────────────
   Prompt enhancement for the text → image step
   ───────────────────────────────────────────────────────────── */

/**
 * Augment the user's free-form prompt into something trellis can turn
 * into a clean 3D mesh: single subject, neutral background, centered,
 * no humans / no text / no logos, even studio light.
 */
function enhancePromptForMesh(userPrompt: string): string {
  const clean = userPrompt.trim().replace(/\s+/g, " ");
  return [
    `Single isolated product photograph of ${clean}.`,
    "Centered subject on a clean neutral background (white or very light grey).",
    "Studio softbox lighting, even illumination, minimal shadow, full subject visible.",
    "Sharp focus across the entire subject, high detail, premium product photography aesthetic.",
    "No humans, no hands, no text, no logos, no watermarks, no on-image typography.",
  ].join(" ");
}

/* ─────────────────────────────────────────────────────────────
   Public API
   ───────────────────────────────────────────────────────────── */

function makeFallback(
  input: Model3DInput,
  startedAt: number,
  error: string,
  extras: Partial<Model3DFallback> = {},
): Model3DFallback {
  return {
    status: "fallback",
    mode: input.mode,
    modelUrl: "",
    modelType: "glb",
    prompt: input.mode === "text_to_3d" ? input.prompt : undefined,
    sourceImageUrl: input.mode === "image_to_3d" ? input.imageUrl : undefined,
    error,
    durationMs: Date.now() - startedAt,
    ...extras,
  };
}

/**
 * Generate a 3D model via fal.ai. Always resolves — never throws.
 */
export async function generateModel3D(
  input: Model3DInput,
): Promise<Model3DResult> {
  const startedAt = Date.now();

  // 1) Cheap validation: trust the route, but be defensive.
  if (input.mode === "text_to_3d") {
    if (!input.prompt?.trim()) {
      return makeFallback(input, startedAt, "empty prompt");
    }
  } else if (input.mode === "image_to_3d") {
    if (!input.imageUrl?.trim()) {
      return makeFallback(input, startedAt, "empty imageUrl");
    }
  } else {
    return makeFallback(input, startedAt, "unknown mode");
  }

  // 2) Make sure FAL is configured.
  if (!ensureFalConfigured()) {
    return makeFallback(input, startedAt, "FAL_KEY missing or placeholder");
  }

  // 3) Image-to-3D — straight shot through trellis.
  if (input.mode === "image_to_3d") {
    const rawImage = input.imageUrl.trim();

    // Hoist `data:` URLs to fal.storage so trellis can fetch them.
    const hoisted = await hoistImageUrl(rawImage);
    if (!hoisted.ok) {
      return makeFallback(input, startedAt, hoisted.error);
    }

    const trellis = await callTrellis(hoisted.url);
    if (!trellis.ok) {
      return makeFallback(input, startedAt, trellis.error, {
        sourceImageUrl: hoisted.url,
      });
    }
    return {
      status: "generated",
      mode: "image_to_3d",
      modelUrl: trellis.url,
      modelType: "glb",
      // Persist the hoisted (public) URL — that's what's actually
      // viewable / shareable across reloads, not the data URL the
      // browser sent in.
      sourceImageUrl: hoisted.url,
      durationMs: Date.now() - startedAt,
    };
  }

  // 4) Text-to-3D — chain flux → trellis.
  const enhanced = enhancePromptForMesh(input.prompt);
  const visual = await generateOneVisual({
    prompt: enhanced,
    visualType: "product_mockup",
    imageSize: "square_hd",
  });

  if (visual.status !== "generated" || !visual.imageUrl) {
    return makeFallback(input, startedAt, `intermediate image failed: ${visual.error ?? "unknown"}`);
  }

  // Don't expose the placeholder URL to trellis — it's not a real image.
  if (visual.imageUrl.startsWith("/")) {
    return makeFallback(input, startedAt, "intermediate image returned local placeholder");
  }

  const trellis = await callTrellis(visual.imageUrl);
  if (!trellis.ok) {
    return makeFallback(input, startedAt, trellis.error, {
      intermediateImageUrl: visual.imageUrl,
    });
  }

  return {
    status: "generated",
    mode: "text_to_3d",
    modelUrl: trellis.url,
    modelType: "glb",
    prompt: input.prompt,
    intermediateImageUrl: visual.imageUrl,
    durationMs: Date.now() - startedAt,
  };
}
